//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class bd01_org
    {
        public string org_id { get; set; }
        public string org_name { get; set; }
        public string org_address { get; set; }
        public string org_tel { get; set; }
        public string org_contact { get; set; }
        public bool org_visible { get; set; }
        public string org_group { get; set; }
        public System.DateTime make_date { get; set; }
    }
}
