//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class bd03_user
    {
        public string user_org { get; set; }
        public string user_dept { get; set; }
        public string user_id { get; set; }
        public string user_pwd { get; set; }
        public string user_name { get; set; }
        public string user_sex { get; set; }
        public string user_mail { get; set; }
        public string user_tel { get; set; }
        public int auth_type { get; set; }
        public bool usable { get; set; }
        public System.DateTime make_date { get; set; }
        public System.DateTime modify_date { get; set; }
        public string maker_id { get; set; }
    }
}
