//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm01_soft_keep_main
    {
        public string year { get; set; }
        public string org { get; set; }
        public string dept { get; set; }
        public string soft_id { get; set; }
        public string soft_name { get; set; }
        public string user_id { get; set; }
        public string soft_type { get; set; }
        public string soft_sn { get; set; }
        public string soft_for { get; set; }
        public string soft_work_on { get; set; }
        public Nullable<int> soft_max_user { get; set; }
        public Nullable<int> soft_number { get; set; }
        public string soft_platform { get; set; }
        public string soft_from { get; set; }
        public string soft_from_unit { get; set; }
        public string soft_keeper { get; set; }
        public string soft_doc { get; set; }
        public Nullable<System.DateTime> install_date { get; set; }
        public string install_place { get; set; }
        public string memo { get; set; }
    }
}
