//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm02_soft_keep_detail
    {
        public string year { get; set; }
        public string org { get; set; }
        public string dept { get; set; }
        public string soft_id { get; set; }
        public string detail_id { get; set; }
        public string keep_org { get; set; }
        public string keep_man { get; set; }
        public string use_org { get; set; }
        public string use_man { get; set; }
        public string soft_ver { get; set; }
        public Nullable<int> soft_cost { get; set; }
        public Nullable<int> auth_number { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string decrease_reason { get; set; }
        public string decrease_handle { get; set; }
        public string detail_memo { get; set; }
    }
}
