//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSEntities : DbContext
    {
        public SMSEntities()
            : base("name=SMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bd01_org> bd01_org { get; set; }
        public virtual DbSet<bd02_dept> bd02_dept { get; set; }
        public virtual DbSet<bd03_user> bd03_user { get; set; }
        public virtual DbSet<sm01_soft_keep_main> sm01_soft_keep_main { get; set; }
        public virtual DbSet<sm02_soft_keep_detail> sm02_soft_keep_detail { get; set; }
    }
}
